services:

  mongo:
    image: mongo
    hostname: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    restart: unless-stopped
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({ _id:'rs0',members:[{_id:0,host:'mongo:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 60s
      start_period: 0s
      start_interval: 1s
      retries: 20
    volumes:
      - mongo:/data/db
    networks:
      usdc-events-api-network:

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      usdc-events-api-network:

volumes:
  mongo:

networks:
  usdc-events-api-network:
