services:

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - usdc-events-api-volume:/data/db
    networks:
      usdc-events-api-network:

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      usdc-events-api-network:

volumes:
  usdc-events-api-volume:

networks:
  usdc-events-api-network:
